#ifndef INSTRUCTION_H
#define INSTRUCTION_H

#define INST_LOADLIB 0
#define INST_SETARG 1
#define INST_CALL 2
#define INST_GOTO 3
#define INST_ADD 4
#define INST_SUB 5
#define INST_CMP 6
#define INST_CL 7
#define INST_CH 8
#define INST_CE 9
#define INST_INC 10
#define INST_DEC 11
#define INST_iPSH 12
#define INST_vPSH 13
#define INST_POP 14
#define INST_SSPP 15
#define INST_iGETL 16
#define INST_iSSPP 17
#define INST_iADD 18
#define INST_iSUB 19
#define INST_iCMP 20
#define INST_AND 21
#define INST_iAND 22
#define INST_OR 23
#define INST_iOR 24
#define INST_XOR 25
#define INST_iXOR 26
#define INST_iREF 27
#define INST_iPOP 28
#define INST_INVOKE 29
#define INST_RETURN 30
#define INST_GSPP 31
#define INST_CNE 32
#define INST_CNH 33
#define INST_CNL 34
#define INST_CHKERR 35
#define INST_EOF 65535

#define INST_LOADLIB_S 2
#define INST_SETARG_S 5
#define INST_CALL_S 2
#define INST_GOTO_S 4
#define INST_ADD_S 8
#define INST_SUB_S 8
#define INST_CMP_S 8
#define INST_CL_S 0
#define INST_CH_S 0
#define INST_CE_S 0
#define INST_INC_S 4
#define INST_DEC_S 4
#define INST_iPSH_S 4
#define INST_vPSH_S 2
#define INST_POP_S 8
#define INST_SSPP_S 4
#define INST_iGETL_S 8
#define INST_iSSPP_S 4
#define INST_iADD_S 8
#define INST_iSUB_S 8
#define INST_iCMP_S 8
#define INST_AND_S 8
#define INST_iAND_S 8
#define INST_OR_S 8
#define INST_iOR_S 8
#define INST_XOR_S 8
#define INST_iXOR_S 8
#define INST_iREF_S 8
#define INST_iPOP_S 8
#define INST_INVOKE_S 4
#define INST_RETURN_S 0
#define INST_GSPP_S 4
#define INST_CNE_S 0
#define INST_CNH_S 0
#define INST_CNL_S 0
#define INST_CHKERR_S 4
#define INST_EOF_S 0

#endif